// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVsNiAYeaJjtyyJc1yj89zf93dY9i3cHY',
    appId: '1:568548219637:web:1723404d22eb84501dc3bc',
    messagingSenderId: '568548219637',
    projectId: 'final-project2000202',
    authDomain: 'final-project2000202.firebaseapp.com',
    storageBucket: 'final-project2000202.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHPKGphZOL-i4D3RP70pOxWeSFwyngkwA',
    appId: '1:568548219637:android:48d7b62f613781c51dc3bc',
    messagingSenderId: '568548219637',
    projectId: 'final-project2000202',
    storageBucket: 'final-project2000202.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_qf9MzG3MSzNTrsXc_exaQZv5CPnV2W4',
    appId: '1:568548219637:ios:13a75c4eb3ad79b21dc3bc',
    messagingSenderId: '568548219637',
    projectId: 'final-project2000202',
    storageBucket: 'final-project2000202.appspot.com',
    iosBundleId: 'com.example.saatRecruitment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_qf9MzG3MSzNTrsXc_exaQZv5CPnV2W4',
    appId: '1:568548219637:ios:13a75c4eb3ad79b21dc3bc',
    messagingSenderId: '568548219637',
    projectId: 'final-project2000202',
    storageBucket: 'final-project2000202.appspot.com',
    iosBundleId: 'com.example.saatRecruitment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVsNiAYeaJjtyyJc1yj89zf93dY9i3cHY',
    appId: '1:568548219637:web:171de911a5d096a31dc3bc',
    messagingSenderId: '568548219637',
    projectId: 'final-project2000202',
    authDomain: 'final-project2000202.firebaseapp.com',
    storageBucket: 'final-project2000202.appspot.com',
  );
}
